import { GiftCardBrand } from '../types';

export const giftCardBrands: GiftCardBrand[] = [
  {
    id: 'amazon',
    name: 'Amazon Pay',
    logo: 'https://logo.clearbit.com/amazon.in',
    category: 'Shopping',
    discount: 0.4,
    denominations: [100, 500, 1000, 2000],
    cardImage: 'https://images.ctfassets.net/zw48pl1isxmc/53n33k5wSo9sP3j2x1N34h/59a7f3de6c52a06f3b72ed2a15f0d8a5/amazon_gift_card.png',
    dealImage: 'https://images.unsplash.com/photo-1594950444552-8071a63c1248?q=80&w=2960&auto=format&fit=crop',
    redemptionSteps: ['Login to Amazon.in', 'Go to "Add Gift Card" in your account', 'Enter the 16-digit code', 'The amount will be added to your Amazon Pay balance'],
    terms: ['Comes with 12-month validity.', 'Gift cards, once purchased, cannot be cancelled or refunded.'],
  },
  {
    id: 'zepto',
    name: 'Zepto',
    logo: 'https://logo.clearbit.com/zeptonow.com',
    category: 'Food',
    discount: 3.5,
    denominations: [100, 200, 500, 1000],
    cardImage: 'https://cdn.dribbble.com/userupload/11266016/file/original-b184144e53e1f57b6d1732047385f8c8.png',
    redemptionSteps: ['Login to Zepto Platform', 'Click on My profile / Settings', 'Go to Zepto Cash & Gift Card', 'Click on "Add Card" option to add the Gift card', 'Enter 16 Digit Card Number and 6 Digit PIN and Submit'],
    terms: ['Valid for 1 year.', 'Cannot be exchanged for cash.'],
  },
  {
    id: 'pvr',
    name: 'PVR Cinemas',
    logo: 'https://logo.clearbit.com/pvrcinemas.com',
    category: 'Entertainment',
    discount: 13.5,
    denominations: [200, 500, 1000, 1500],
    cardImage: 'https://cdn.dribbble.com/users/176778/screenshots/3716617/media/6132798f454477818a7c2c9d8c366e6b.png',
    redemptionSteps: ['Log on to the PVR Cinemas website or mobile app.', 'Select your movie, showtime, and seats.', 'On the payment page, select "Gift Card" as the payment option.', 'Enter your Gift Card number and PIN.'],
    terms: ['Valid for movie tickets and F&B.', 'Cannot be redeemed at the box office.'],
  },
  {
    id: 'bigbasket',
    name: 'Bigbasket',
    logo: 'https://logo.clearbit.com/bigbasket.com',
    category: 'Shopping',
    discount: 5,
    denominations: [100, 250, 500, 1000],
    cardImage: 'https://cdn.dribbble.com/users/253915/screenshots/11691238/media/6b68b75e72d2449706a142e05f0a2569.png',
    dealImage: 'https://images.unsplash.com/photo-1583258292688-d021e9505262?q=80&w=2850&auto=format&fit=crop',
    redemptionSteps: ['Login to your Bigbasket account.', 'Go to your account and click on "My Gift Cards".', 'Enter the gift card code and click on "Add to Wallet".'],
    terms: ['The gift card can be used for multiple orders.', 'The gift card is valid for 12 months from the date of issue.'],
  },
  {
    id: 'zomato',
    name: 'Zomato',
    logo: 'https://logo.clearbit.com/zomato.com',
    category: 'Food',
    discount: 2.0,
    denominations: [250, 500, 1000],
    cardImage: 'https://cdn.dribbble.com/users/2281085/screenshots/17158739/media/689a7421f21133f5d5e894f27d5d143c.png',
    redemptionSteps: ['Open Zomato App.', 'Go to your profile and tap on "Claim gift card".', 'Enter the unique code.', 'The amount gets added to your Zomato Credits.'],
    terms: ['Valid for 1 year.', 'Can be used to order food online from restaurants.'],
  },
];